--------------------------------------------------------
-- Archivo creado  - domingo-marzo-31-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ASIGNACION_DIAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."ASIGNACION_DIAS" 
   (	"IDASIGNAIONDIA" NUMBER(*,0), 
	"IDDIA" NUMBER(*,0), 
	"IDCURSO" NUMBER(*,0), 
	"IDLUGAR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table ASIGNACIONES_ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" 
   (	"IDASIGNACION" NUMBER(*,0), 
	"IDESTUDIANTE" NUMBER(*,0), 
	"IDEXAMENES" NUMBER(*,0), 
	"HORA_INICIO" DATE, 
	"HORA_FIN" DATE, 
	"FECHA_ASIGNACION" DATE, 
	"NOTA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table ASIGNACIONES_PREGUNTAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" 
   (	"IDASIGNACION" NUMBER(*,0), 
	"IDESTUDIANTE" NUMBER(*,0), 
	"IDPREGUNTAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table BANCOPREGUNTAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."BANCOPREGUNTAS" 
   (	"IDBANCO" NUMBER(*,0), 
	"IDEXAMENES" NUMBER(*,0), 
	"IDPREGUNTAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table CONTENIDOS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."CONTENIDOS" 
   (	"IDCONTENIDO" NUMBER(*,0), 
	"DESCRICONTENIDO" VARCHAR2(40 BYTE), 
	"IDUNIDAD" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table CURSOS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."CURSOS" 
   (	"IDCURSO" NUMBER(*,0), 
	"NOMBRECURSO" VARCHAR2(40 BYTE), 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"IDDOCENTE" NUMBER(*,0), 
	"IDMATERIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table DIAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."DIAS" 
   (	"IDDIA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table DOCENTES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."DOCENTES" 
   (	"IDDOCENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"APELLIDO" VARCHAR2(40 BYTE), 
	"USUARIO" VARCHAR2(40 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"DIRECCION" VARCHAR2(40 BYTE), 
	"IDINSTITUCION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table EDIFICIOS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."EDIFICIOS" 
   (	"IDEDIFICIO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table ESTADOS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."ESTADOS" 
   (	"IDESTADO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."ESTUDIANTES" 
   (	"IDESTUDIANTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"APELLIDO" VARCHAR2(40 BYTE), 
	"USUARIO" VARCHAR2(40 BYTE), 
	"correo_electronico " VARCHAR2(40 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"IDCURSO" NUMBER(*,0), 
	"IDGRUPO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table EXAMENES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."EXAMENES" 
   (	"IDEXAMENEN" NUMBER(*,0), 
	"TITULO" VARCHAR2(40 BYTE), 
	"FECHAYHORACREACION" DATE, 
	"DURACIONEXAMEN" NUMBER(*,0), 
	"CANTIDADPREGUNTAS" NUMBER(*,0), 
	"CALIFICACION" FLOAT(126), 
	"IDHORARIO" NUMBER(*,0), 
	"IDCURSO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table GRUPOS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."GRUPOS" 
   (	"IDGRUPO" NUMBER(*,0), 
	"NOMBREGRUPO" VARCHAR2(40 BYTE), 
	"AÑOACATEMICO" DATE, 
	"IDDOCENTE_TUTOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table HORARIOS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."HORARIOS" 
   (	"IDHORARIO" NUMBER(*,0), 
	"HORA_INICIO" DATE, 
	"HORA_FIN" DATE, 
	"IDASIGNAIONDIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table INSTITUCIONES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."INSTITUCIONES" 
   (	"IDINSTITUCION" NUMBER(*,0), 
	"NOMBRENINSTITUCION" VARCHAR2(40 BYTE), 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"DIRECCION" VARCHAR2(40 BYTE), 
	"TELEFONO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table LUGARES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."LUGARES" 
   (	"IDLUGAR" NUMBER(*,0), 
	"IDEDIFICIO" NUMBER(*,0), 
	"IDSALON" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table MATERIAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."MATERIAS" 
   (	"IDMATERIA" NUMBER(*,0), 
	"NOMBRE" NUMBER(*,0), 
	"DESCRIPCION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."PREGUNTAS" 
   (	"IDPREGUNTA" NUMBER(*,0), 
	"ENUNCIADO" VARCHAR2(40 BYTE), 
	"IDEXAMENES" NUMBER(*,0), 
	"IDTEMA" NUMBER(*,0), 
	"IDESTADO" NUMBER(*,0), 
	"IDTIPOPREGUNTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."RESPUESTAS" 
   (	"IDRESPUESTA" NUMBER(*,0), 
	"OPCIONRESPUESTA" VARCHAR2(40 BYTE), 
	"CORRECTA" VARCHAR2(40 BYTE), 
	"IDPREGUNTAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAS_ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" 
   (	"IDRESPUESTAESTUDIANTE" NUMBER(*,0), 
	"IDESTUDIANTE" NUMBER(*,0), 
	"IDEXAMENES" NUMBER(*,0), 
	"IDPREGUNTAS" NUMBER(*,0), 
	"IDRESPUESTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table SALONES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."SALONES" 
   (	"IDSALON" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table TEMAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."TEMAS" 
   (	"IDTEMA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"IDCONTENIDO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table TEMAS_EXAMENES
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."TEMAS_EXAMENES" 
   (	"IDTEMA_EXAMEN" NUMBER(*,0), 
	"IDEXAMENES" NUMBER(*,0), 
	"IDTEMA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TRANSACCIONES" ;
--------------------------------------------------------
--  DDL for Table TIPOSPREGUNTAS
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."TIPOSPREGUNTAS" 
   (	"IDTIPOPREGUNTA" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
--------------------------------------------------------
--  DDL for Table UNIDADESESTUDIO
--------------------------------------------------------

  CREATE TABLE "EDUQUIZ"."UNIDADESESTUDIO" 
   (	"IDUNIDAD" NUMBER(*,0), 
	"NOMBRE_UNIDAD" VARCHAR2(40 BYTE), 
	"DESCRIPCION" VARCHAR2(40 BYTE), 
	"IDMATERIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATOS" ;
REM INSERTING into EDUQUIZ.ASIGNACION_DIAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.ASIGNACIONES_ESTUDIANTES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.ASIGNACIONES_PREGUNTAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.BANCOPREGUNTAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.CONTENIDOS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.CURSOS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.DIAS
SET DEFINE OFF;
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('1','Lunes');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('2','Martes');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('3','Miercoles');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('4','Jueves');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('5','Viernes');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('6','Sabado');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('7','Domingo');
REM INSERTING into EDUQUIZ.DOCENTES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.EDIFICIOS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.ESTADOS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.ESTUDIANTES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.EXAMENES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.GRUPOS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.HORARIOS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.INSTITUCIONES
SET DEFINE OFF;
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('1','Universidad Nacional','Universidad pública de prestigio','Avenida Principal 123','3145551234');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('2','Colegio Técnico','Institución de educación técnica','Calle Secundaria 456','3235557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('3','Academia de Idiomas','Centro de enseñanza de idiomas','Plaza Central 789','3135559876');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('4','Escuela Primaria N°1','Educación básica primaria','Avenida del Parque 234','3115553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('6','Universidad Privada','Institución universitaria privada','Calle Principal 890','3045558901');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('7','Colegio Bilingüe','Enseñanza en dos idiomas','Avenida Internacional 345','3155552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('8','Centro de Capacitación','Cursos de formación profesional','Calle Comercial 678','3165557678');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('9','Escuela Secundaria N°2','Educación media secundaria','Bulevar Estudiantil 901','3155559012');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('10','Instituto Tecnológico','Formación en carreras tecnológicas','Avenida Tecnológica 234','3035554567');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('11','Academia de Música','Enseñanza de música y artes escénicas','Plaza de la Música 567','3235557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('13','Universidad Agrícola','Institución especializada en agronomía','Ruta Rural 345','3135556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('14','Escuela de Artes y Oficios','Formación en oficios y manualidades','Avenida Artesanal 678','3175552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('16','Colegio Técnico N°3','Institución de educación técnica','Calle Industrial 234','3175553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('17','Universidad Virtual','Educación en línea y a distancia','Avenida Virtual 567','3255556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('19','Instituto de Liderazgo','Desarrollo de habilidades de liderazgo','Calle Empresarial 345','3235554567');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('21','Colegio Técnico N°4','Institución de educación técnica','Avenida Industrial 901','3165550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('23','Escuela de Deportes','Formación en disciplinas deportivas','Calle Olímpica 567','3045552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('24','Instituto de Negocios','Educación en administración y negocios','Avenida Empresarial 890','3255557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('27','Escuela de Idiomas','Enseñanza intensiva de idiomas','Avenida Lingüística 901','3165552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('29','Colegio de Artes Escénicas','Formación en teatro, danza y música','Plaza del Espectáculo 567','3175550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('31','Escuela de Formación Docente','Preparación de futuros maestros','Calle Pedagógica 345','3235559012');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('33','Universidad de Artes Visuales','Institución dedicada a las bellas artes','Plaza Artística 901','3175557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('34','Colegio de Música','Formación musical integral','Avenida Melódica 234','3175553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('36','Escuela de Periodismo','Preparación de futuros periodistas','Avenida Informativa 890','3155552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('37','Academia de Fotografía','Enseñanza de técnicas fotográficas','Plaza del Lente 345','3235557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('5','Instituto de Arte','Formación en artes visuales','Bulevar de las Artes 567','3045556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('12','Colegio Montessori','Educación basada en método Montessori','Calle Alternativa 890','3255550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('15','Instituto de Idiomas','Centro de enseñanza de lenguas','Plaza Internacional 901','3165557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('22','Universidad de Ciencias','Institución de ciencias naturales','Ruta Científica 234','3045556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('18','Escuela de Bellas Artes','Formación en artes visuales','Bulevar Artístico 890','3235559012');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('20','Academia de Danza','Enseñanza de danza','Plaza del Ballet 678','3135557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('28','Universidad Tecnológica','Institución de ingenieria/tecnología','Bulevar Innovador 234','3185557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('25','Academia de Cocina','Enseñanza de gastronomía/culinaria','Plaza Gastronómica 345','3235553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('26','Instituto de Diseño','Formación en diseño gráfico','Calle Creativa 678','3155558901');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('30','Instituto de Computación','Educación en programación/informatica','Avenida Digital 890','3185556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('32','Academia de Robótica','Enseñanza de robótica/automatización','Bulevar Tecnológico 678','3175554567');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('35','Instituto de Cinematografía','Educación en cine y producción','Calle del Cine 567','3165558901');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('38','Colegio de Diseño de Interiores','Formación en decoración e interiores','Bulevar Estético 678','3235550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('39','Universidad de Moda','Institución de diseño de moda','Calle de la Moda 901','3155556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('40','Instituto de Turismo','Educación de turismo y hotelería','Avenida del Viajero 234','3165559012');
REM INSERTING into EDUQUIZ.LUGARES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.MATERIAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.PREGUNTAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.RESPUESTAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.RESPUESTAS_ESTUDIANTES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.SALONES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.TEMAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.TEMAS_EXAMENES
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.TIPOSPREGUNTAS
SET DEFINE OFF;
REM INSERTING into EDUQUIZ.UNIDADESESTUDIO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index NOMBRE_CURSOS
--------------------------------------------------------

  CREATE INDEX "EDUQUIZ"."NOMBRE_CURSOS" ON "EDUQUIZ"."CURSOS" ("NOMBRECURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_RESPUESTAS_ESTUDIANTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_RESPUESTAS_ESTUDIANTES" ON "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" ("IDRESPUESTAESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_ASIGNACION_DIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_ASIGNACION_DIAS" ON "EDUQUIZ"."ASIGNACION_DIAS" ("IDASIGNAIONDIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_UNIDADESESTUDIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_UNIDADESESTUDIO" ON "EDUQUIZ"."UNIDADESESTUDIO" ("IDUNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_RESPUESTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_RESPUESTAS" ON "EDUQUIZ"."RESPUESTAS" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_SALONES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_SALONES" ON "EDUQUIZ"."SALONES" ("IDSALON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_CONTENIDOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_CONTENIDOS" ON "EDUQUIZ"."CONTENIDOS" ("IDCONTENIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_MATERIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_MATERIAS" ON "EDUQUIZ"."MATERIAS" ("IDMATERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_DOCENTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_DOCENTES" ON "EDUQUIZ"."DOCENTES" ("IDDOCENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_UNIDADES
--------------------------------------------------------

  CREATE INDEX "EDUQUIZ"."NOMBRE_UNIDADES" ON "EDUQUIZ"."UNIDADESESTUDIO" ("NOMBRE_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_DIAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_DIAS" ON "EDUQUIZ"."DIAS" ("IDDIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_EXAMENES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_EXAMENES" ON "EDUQUIZ"."EXAMENES" ("IDEXAMENEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_TEMAS_EXAMENES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_TEMAS_EXAMENES" ON "EDUQUIZ"."TEMAS_EXAMENES" ("IDTEMA_EXAMEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_GRUPOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_GRUPOS" ON "EDUQUIZ"."GRUPOS" ("IDGRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_PREGUNTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_PREGUNTAS" ON "EDUQUIZ"."PREGUNTAS" ("IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_HORARIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_HORARIOS" ON "EDUQUIZ"."HORARIOS" ("IDHORARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_CURSOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_CURSOS" ON "EDUQUIZ"."CURSOS" ("IDCURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_BANCOSPREGUNTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_BANCOSPREGUNTAS" ON "EDUQUIZ"."BANCOPREGUNTAS" ("IDBANCO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_ASIGNACIONES_ESTUDIANTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_ASIGNACIONES_ESTUDIANTES" ON "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" ("IDASIGNACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_TEMAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_TEMAS" ON "EDUQUIZ"."TEMAS" ("IDTEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_ESTADOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_ESTADOS" ON "EDUQUIZ"."ESTADOS" ("IDESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_ASIGNACIONES_PREGUNTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_ASIGNACIONES_PREGUNTAS" ON "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" ("IDASIGNACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_ESTUDIANTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_ESTUDIANTES" ON "EDUQUIZ"."ESTUDIANTES" ("IDESTUDIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_TIPOSPREGUNTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_TIPOSPREGUNTAS" ON "EDUQUIZ"."TIPOSPREGUNTAS" ("IDTIPOPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_GRUPOS
--------------------------------------------------------

  CREATE INDEX "EDUQUIZ"."NOMBRE_GRUPOS" ON "EDUQUIZ"."GRUPOS" ("NOMBREGRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_MATERIAS
--------------------------------------------------------

  CREATE INDEX "EDUQUIZ"."NOMBRE_MATERIAS" ON "EDUQUIZ"."MATERIAS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_EDIFICIOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_EDIFICIOS" ON "EDUQUIZ"."EDIFICIOS" ("IDEDIFICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_TEMAS
--------------------------------------------------------

  CREATE INDEX "EDUQUIZ"."NOMBRE_TEMAS" ON "EDUQUIZ"."TEMAS" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index NOMBRE_INSTITUCIONES
--------------------------------------------------------

  CREATE INDEX "EDUQUIZ"."NOMBRE_INSTITUCIONES" ON "EDUQUIZ"."INSTITUCIONES" ("NOMBRENINSTITUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_INSTITUCIONES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_INSTITUCIONES" ON "EDUQUIZ"."INSTITUCIONES" ("IDINSTITUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  DDL for Index ID_LUGARES
--------------------------------------------------------

  CREATE UNIQUE INDEX "EDUQUIZ"."ID_LUGARES" ON "EDUQUIZ"."LUGARES" ("IDLUGAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX" ;
--------------------------------------------------------
--  Constraints for Table GRUPOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."GRUPOS" ADD CONSTRAINT "GRUPOS_PK" PRIMARY KEY ("IDGRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."GRUPOS" MODIFY ("IDDOCENTE_TUTOR" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."GRUPOS" MODIFY ("AÑOACATEMICO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."GRUPOS" MODIFY ("NOMBREGRUPO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."GRUPOS" MODIFY ("IDGRUPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEMAS_EXAMENES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."TEMAS_EXAMENES" ADD CONSTRAINT "TEMAS_EXAMENES_PK" PRIMARY KEY ("IDTEMA_EXAMEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."TEMAS_EXAMENES" MODIFY ("IDTEMA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."TEMAS_EXAMENES" MODIFY ("IDEXAMENES" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."TEMAS_EXAMENES" MODIFY ("IDTEMA_EXAMEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEMAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."TEMAS" ADD CONSTRAINT "TEMAS_PK" PRIMARY KEY ("IDTEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."TEMAS" MODIFY ("IDCONTENIDO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."TEMAS" MODIFY ("IDTEMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UNIDADESESTUDIO
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."UNIDADESESTUDIO" ADD CONSTRAINT "UNIDADESESTUDIO_PK" PRIMARY KEY ("IDUNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."UNIDADESESTUDIO" MODIFY ("IDMATERIA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."UNIDADESESTUDIO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."UNIDADESESTUDIO" MODIFY ("NOMBRE_UNIDAD" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."UNIDADESESTUDIO" MODIFY ("IDUNIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."DIAS" ADD CONSTRAINT "DIAS_PK" PRIMARY KEY ("IDDIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."DIAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DIAS" MODIFY ("IDDIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANCOPREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."BANCOPREGUNTAS" ADD CONSTRAINT "BANCOSPREGUNTAS_PK" PRIMARY KEY ("IDBANCO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."BANCOPREGUNTAS" MODIFY ("IDPREGUNTAS" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."BANCOPREGUNTAS" MODIFY ("IDEXAMENES" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."BANCOPREGUNTAS" MODIFY ("IDBANCO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASIGNACIONES_PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" ADD CONSTRAINT "ASIGNACIONES_PREGUNTAS_PK" PRIMARY KEY ("IDASIGNACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" MODIFY ("IDPREGUNTAS" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" MODIFY ("IDESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" MODIFY ("IDASIGNACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOSPREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."TIPOSPREGUNTAS" ADD CONSTRAINT "TIPOSPREGUNTAS_PK" PRIMARY KEY ("IDTIPOPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."TIPOSPREGUNTAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."TIPOSPREGUNTAS" MODIFY ("IDTIPOPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_PK" PRIMARY KEY ("IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" MODIFY ("IDTIPOPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" MODIFY ("IDESTADO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" MODIFY ("IDTEMA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" MODIFY ("IDEXAMENES" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" MODIFY ("ENUNCIADO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" ADD CONSTRAINT "ESTUDIANTES_PK" PRIMARY KEY ("IDESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("IDGRUPO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("IDCURSO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("correo_electronico " NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" MODIFY ("IDESTUDIANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURSOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."CURSOS" ADD CONSTRAINT "CURSOS_PK" PRIMARY KEY ("IDCURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."CURSOS" MODIFY ("IDMATERIA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."CURSOS" MODIFY ("IDDOCENTE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."CURSOS" MODIFY ("IDCURSO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCENTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."DOCENTES" ADD CONSTRAINT "DOCENTES_PK" PRIMARY KEY ("IDDOCENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("IDINSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."DOCENTES" MODIFY ("IDDOCENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASIGNACION_DIAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" ADD CONSTRAINT "ASIGNACION_DIAS_PK" PRIMARY KEY ("IDASIGNAIONDIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" MODIFY ("IDLUGAR" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" MODIFY ("IDCURSO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" MODIFY ("IDDIA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" MODIFY ("IDASIGNAIONDIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALONES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."SALONES" ADD CONSTRAINT "SALONES_PK" PRIMARY KEY ("IDSALON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."SALONES" MODIFY ("IDSALON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ESTADOS" ADD CONSTRAINT "ESTADOS_PK" PRIMARY KEY ("IDESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."ESTADOS" MODIFY ("IDESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASIGNACIONES_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" ADD CONSTRAINT "ASIGNACIONES_ESTUDIANTES_PK" PRIMARY KEY ("IDASIGNACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("NOTA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("FECHA_ASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("IDEXAMENES" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("IDESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" MODIFY ("IDASIGNACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HORARIOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."HORARIOS" ADD CONSTRAINT "HORARIOS_PK" PRIMARY KEY ("IDHORARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."HORARIOS" MODIFY ("IDASIGNAIONDIA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."HORARIOS" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."HORARIOS" MODIFY ("HORA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."HORARIOS" MODIFY ("IDHORARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."MATERIAS" ADD CONSTRAINT "MATERIAS_PK" PRIMARY KEY ("IDMATERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."MATERIAS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."MATERIAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."MATERIAS" MODIFY ("IDMATERIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSTITUCIONES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."INSTITUCIONES" ADD CONSTRAINT "INSTITUCIONES_PK" PRIMARY KEY ("IDINSTITUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."INSTITUCIONES" MODIFY ("NOMBRENINSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."INSTITUCIONES" MODIFY ("IDINSTITUCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAS_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" ADD CONSTRAINT "RESPUESTAS_ESTUDIANTES_PK" PRIMARY KEY ("IDRESPUESTAESTUDIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" MODIFY ("IDPREGUNTAS" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" MODIFY ("IDEXAMENES" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" MODIFY ("IDESTUDIANTE" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" MODIFY ("IDRESPUESTAESTUDIANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTENIDOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."CONTENIDOS" ADD CONSTRAINT "CONTENIDOS_PK" PRIMARY KEY ("IDCONTENIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."CONTENIDOS" MODIFY ("IDUNIDAD" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."CONTENIDOS" MODIFY ("DESCRICONTENIDO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."CONTENIDOS" MODIFY ("IDCONTENIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LUGARES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."LUGARES" ADD CONSTRAINT "LUGARES_PK" PRIMARY KEY ("IDLUGAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."LUGARES" MODIFY ("IDSALON" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."LUGARES" MODIFY ("IDEDIFICIO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."LUGARES" MODIFY ("IDLUGAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."RESPUESTAS" ADD CONSTRAINT "RESPUESTAS_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."RESPUESTAS" MODIFY ("IDPREGUNTAS" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS" MODIFY ("CORRECTA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS" MODIFY ("OPCIONRESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."RESPUESTAS" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXAMENES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("IDCURSO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("IDHORARIO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("CALIFICACION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("DURACIONEXAMEN" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("FECHAYHORACREACION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" MODIFY ("IDEXAMENEN" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EXAMENES" ADD CONSTRAINT "EXAMENES_PK" PRIMARY KEY ("IDEXAMENEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EDIFICIOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."EDIFICIOS" ADD CONSTRAINT "EDIFICIOS_PK" PRIMARY KEY ("IDEDIFICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_INDEX"  ENABLE;
  ALTER TABLE "EDUQUIZ"."EDIFICIOS" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "EDUQUIZ"."EDIFICIOS" MODIFY ("IDEDIFICIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASIGNACION_DIAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" ADD CONSTRAINT "ASIGNACION_DIAS_CURSOS_FK" FOREIGN KEY ("IDCURSO")
	  REFERENCES "EDUQUIZ"."CURSOS" ("IDCURSO") ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" ADD CONSTRAINT "ASIGNACION_DIAS_DIAS_FK" FOREIGN KEY ("IDDIA")
	  REFERENCES "EDUQUIZ"."DIAS" ("IDDIA") ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACION_DIAS" ADD CONSTRAINT "ASIGNACION_DIAS_LUGARES_FK" FOREIGN KEY ("IDLUGAR")
	  REFERENCES "EDUQUIZ"."LUGARES" ("IDLUGAR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASIGNACIONES_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" ADD CONSTRAINT "ASIG_ESTUD_ESTUD_FK" FOREIGN KEY ("IDESTUDIANTE")
	  REFERENCES "EDUQUIZ"."ESTUDIANTES" ("IDESTUDIANTE") ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_ESTUDIANTES" ADD CONSTRAINT "ASIG_ESTUD_EXAM_FK" FOREIGN KEY ("IDEXAMENES")
	  REFERENCES "EDUQUIZ"."EXAMENES" ("IDEXAMENEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASIGNACIONES_PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" ADD CONSTRAINT "ASIG_PREG_ESTUD_FK" FOREIGN KEY ("IDESTUDIANTE")
	  REFERENCES "EDUQUIZ"."ESTUDIANTES" ("IDESTUDIANTE") ENABLE;
  ALTER TABLE "EDUQUIZ"."ASIGNACIONES_PREGUNTAS" ADD CONSTRAINT "ASIG_PREG_PREG_FK" FOREIGN KEY ("IDPREGUNTAS")
	  REFERENCES "EDUQUIZ"."PREGUNTAS" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BANCOPREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."BANCOPREGUNTAS" ADD CONSTRAINT "BANCOSPREGUNTAS_EXAMENES_FK" FOREIGN KEY ("IDEXAMENES")
	  REFERENCES "EDUQUIZ"."EXAMENES" ("IDEXAMENEN") ENABLE;
  ALTER TABLE "EDUQUIZ"."BANCOPREGUNTAS" ADD CONSTRAINT "BANCOSPREGUNTAS_PREGUNTAS_FK" FOREIGN KEY ("IDPREGUNTAS")
	  REFERENCES "EDUQUIZ"."PREGUNTAS" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENIDOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."CONTENIDOS" ADD CONSTRAINT "CONTENIDOS_UNIDADESESTUDIO_FK" FOREIGN KEY ("IDUNIDAD")
	  REFERENCES "EDUQUIZ"."UNIDADESESTUDIO" ("IDUNIDAD") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURSOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."CURSOS" ADD CONSTRAINT "CURSOS_DOCENTES_FK" FOREIGN KEY ("IDDOCENTE")
	  REFERENCES "EDUQUIZ"."DOCENTES" ("IDDOCENTE") ENABLE;
  ALTER TABLE "EDUQUIZ"."CURSOS" ADD CONSTRAINT "CURSOS_MATERIAS_FK" FOREIGN KEY ("IDMATERIA")
	  REFERENCES "EDUQUIZ"."MATERIAS" ("IDMATERIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOCENTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."DOCENTES" ADD CONSTRAINT "DOCENTES_INSTITUCIONES_FK" FOREIGN KEY ("IDINSTITUCION")
	  REFERENCES "EDUQUIZ"."INSTITUCIONES" ("IDINSTITUCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" ADD CONSTRAINT "ESTUDIANTES_CURSOS_FK" FOREIGN KEY ("IDCURSO")
	  REFERENCES "EDUQUIZ"."CURSOS" ("IDCURSO") ENABLE;
  ALTER TABLE "EDUQUIZ"."ESTUDIANTES" ADD CONSTRAINT "ESTUDIANTES_GRUPOS_FK" FOREIGN KEY ("IDGRUPO")
	  REFERENCES "EDUQUIZ"."GRUPOS" ("IDGRUPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXAMENES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."EXAMENES" ADD CONSTRAINT "EXAMENES_CURSOS_FK" FOREIGN KEY ("IDCURSO")
	  REFERENCES "EDUQUIZ"."CURSOS" ("IDCURSO") ENABLE;
  ALTER TABLE "EDUQUIZ"."EXAMENES" ADD CONSTRAINT "EXAMENES_HORARIOS_FK" FOREIGN KEY ("IDHORARIO")
	  REFERENCES "EDUQUIZ"."HORARIOS" ("IDHORARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."GRUPOS" ADD CONSTRAINT "GRUPOS_DOCENTES_FK" FOREIGN KEY ("IDDOCENTE_TUTOR")
	  REFERENCES "EDUQUIZ"."DOCENTES" ("IDDOCENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HORARIOS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."HORARIOS" ADD CONSTRAINT "HORARIOS_ASIGNACION_DIAS_FK" FOREIGN KEY ("IDASIGNAIONDIA")
	  REFERENCES "EDUQUIZ"."ASIGNACION_DIAS" ("IDASIGNAIONDIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LUGARES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."LUGARES" ADD CONSTRAINT "LUGARES_EDIFICIOS_FK" FOREIGN KEY ("IDEDIFICIO")
	  REFERENCES "EDUQUIZ"."EDIFICIOS" ("IDEDIFICIO") ENABLE;
  ALTER TABLE "EDUQUIZ"."LUGARES" ADD CONSTRAINT "LUGARES_SALONES_FK" FOREIGN KEY ("IDSALON")
	  REFERENCES "EDUQUIZ"."SALONES" ("IDSALON") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_ESTADOS_FK" FOREIGN KEY ("IDESTADO")
	  REFERENCES "EDUQUIZ"."ESTADOS" ("IDESTADO") ENABLE;
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_TEMAS_FK" FOREIGN KEY ("IDTEMA")
	  REFERENCES "EDUQUIZ"."TEMAS" ("IDTEMA") ENABLE;
  ALTER TABLE "EDUQUIZ"."PREGUNTAS" ADD CONSTRAINT "PREGUNTAS_TIPOSPREGUNTAS_FK" FOREIGN KEY ("IDTIPOPREGUNTA")
	  REFERENCES "EDUQUIZ"."TIPOSPREGUNTAS" ("IDTIPOPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."RESPUESTAS" ADD CONSTRAINT "RESPUESTAS_PREGUNTAS_FK" FOREIGN KEY ("IDPREGUNTAS")
	  REFERENCES "EDUQUIZ"."PREGUNTAS" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAS_ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" ADD CONSTRAINT "RESP_ESTUD_ESTUD_FK" FOREIGN KEY ("IDESTUDIANTE")
	  REFERENCES "EDUQUIZ"."ESTUDIANTES" ("IDESTUDIANTE") ENABLE;
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" ADD CONSTRAINT "RESP_ESTUD_EXAM_FK" FOREIGN KEY ("IDEXAMENES")
	  REFERENCES "EDUQUIZ"."EXAMENES" ("IDEXAMENEN") ENABLE;
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" ADD CONSTRAINT "RESP_ESTUD_PREG_FK" FOREIGN KEY ("IDPREGUNTAS")
	  REFERENCES "EDUQUIZ"."PREGUNTAS" ("IDPREGUNTA") ENABLE;
  ALTER TABLE "EDUQUIZ"."RESPUESTAS_ESTUDIANTES" ADD CONSTRAINT "RESP_ESTUD_RESP_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "EDUQUIZ"."RESPUESTAS" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMAS
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."TEMAS" ADD CONSTRAINT "TEMAS_CONTENIDOS_FK" FOREIGN KEY ("IDCONTENIDO")
	  REFERENCES "EDUQUIZ"."CONTENIDOS" ("IDCONTENIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEMAS_EXAMENES
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."TEMAS_EXAMENES" ADD CONSTRAINT "TEMAS_EXAMENES_EXAMENES_FK" FOREIGN KEY ("IDEXAMENES")
	  REFERENCES "EDUQUIZ"."EXAMENES" ("IDEXAMENEN") ENABLE;
  ALTER TABLE "EDUQUIZ"."TEMAS_EXAMENES" ADD CONSTRAINT "TEMAS_EXAMENES_TEMAS_FK" FOREIGN KEY ("IDTEMA")
	  REFERENCES "EDUQUIZ"."TEMAS" ("IDTEMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UNIDADESESTUDIO
--------------------------------------------------------

  ALTER TABLE "EDUQUIZ"."UNIDADESESTUDIO" ADD CONSTRAINT "UNIDADESESTUDIO_MATERIAS_FK" FOREIGN KEY ("IDMATERIA")
	  REFERENCES "EDUQUIZ"."MATERIAS" ("IDMATERIA") ENABLE;
