Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('1','Lunes');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('2','Martes');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('3','Miercoles');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('4','Jueves');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('5','Viernes');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('6','Sabado');
Insert into EDUQUIZ.DIAS (IDDIA,DESCRIPCION) values ('7','Domingo');

Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('1','Universidad Nacional','Universidad pública de prestigio','Avenida Principal 123','3145551234');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('2','Colegio Técnico','Institución de educación técnica','Calle Secundaria 456','3235557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('3','Academia de Idiomas','Centro de enseñanza de idiomas','Plaza Central 789','3135559876');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('4','Escuela Primaria N°1','Educación básica primaria','Avenida del Parque 234','3115553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('6','Universidad Privada','Institución universitaria privada','Calle Principal 890','3045558901');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('7','Colegio Bilingüe','Enseñanza en dos idiomas','Avenida Internacional 345','3155552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('8','Centro de Capacitación','Cursos de formación profesional','Calle Comercial 678','3165557678');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('9','Escuela Secundaria N°2','Educación media secundaria','Bulevar Estudiantil 901','3155559012');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('10','Instituto Tecnológico','Formación en carreras tecnológicas','Avenida Tecnológica 234','3035554567');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('11','Academia de Música','Enseñanza de música y artes escénicas','Plaza de la Música 567','3235557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('13','Universidad Agrícola','Institución especializada en agronomía','Ruta Rural 345','3135556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('14','Escuela de Artes y Oficios','Formación en oficios y manualidades','Avenida Artesanal 678','3175552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('16','Colegio Técnico N°3','Institución de educación técnica','Calle Industrial 234','3175553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('17','Universidad Virtual','Educación en línea y a distancia','Avenida Virtual 567','3255556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('19','Instituto de Liderazgo','Desarrollo de habilidades de liderazgo','Calle Empresarial 345','3235554567');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('21','Colegio Técnico N°4','Institución de educación técnica','Avenida Industrial 901','3165550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('23','Escuela de Deportes','Formación en disciplinas deportivas','Calle Olímpica 567','3045552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('24','Instituto de Negocios','Educación en administración y negocios','Avenida Empresarial 890','3255557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('27','Escuela de Idiomas','Enseñanza intensiva de idiomas','Avenida Lingüística 901','3165552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('29','Colegio de Artes Escénicas','Formación en teatro, danza y música','Plaza del Espectáculo 567','3175550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('31','Escuela de Formación Docente','Preparación de futuros maestros','Calle Pedagógica 345','3235559012');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('33','Universidad de Artes Visuales','Institución dedicada a las bellas artes','Plaza Artística 901','3175557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('34','Colegio de Música','Formación musical integral','Avenida Melódica 234','3175553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('36','Escuela de Periodismo','Preparación de futuros periodistas','Avenida Informativa 890','3155552345');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('37','Academia de Fotografía','Enseñanza de técnicas fotográficas','Plaza del Lente 345','3235557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('5','Instituto de Arte','Formación en artes visuales','Bulevar de las Artes 567','3045556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('12','Colegio Montessori','Educación basada en método Montessori','Calle Alternativa 890','3255550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('15','Instituto de Idiomas','Centro de enseñanza de lenguas','Plaza Internacional 901','3165557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('22','Universidad de Ciencias','Institución de ciencias naturales','Ruta Científica 234','3045556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('18','Escuela de Bellas Artes','Formación en artes visuales','Bulevar Artístico 890','3235559012');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('20','Academia de Danza','Enseñanza de danza','Plaza del Ballet 678','3135557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('28','Universidad Tecnológica','Institución de ingenieria/tecnología','Bulevar Innovador 234','3185557890');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('25','Academia de Cocina','Enseñanza de gastronomía/culinaria','Plaza Gastronómica 345','3235553456');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('26','Instituto de Diseño','Formación en diseño gráfico','Calle Creativa 678','3155558901');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('30','Instituto de Computación','Educación en programación/informatica','Avenida Digital 890','3185556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('32','Academia de Robótica','Enseñanza de robótica/automatización','Bulevar Tecnológico 678','3175554567');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('35','Instituto de Cinematografía','Educación en cine y producción','Calle del Cine 567','3165558901');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('38','Colegio de Diseño de Interiores','Formación en decoración e interiores','Bulevar Estético 678','3235550123');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('39','Universidad de Moda','Institución de diseño de moda','Calle de la Moda 901','3155556789');
Insert into EDUQUIZ.INSTITUCIONES (IDINSTITUCION,NOMBRENINSTITUCION,DESCRIPCION,DIRECCION,TELEFONO) values ('40','Instituto de Turismo','Educación de turismo y hotelería','Avenida del Viajero 234','3165559012');