CREATE TABLESPACE ts_datos
DATAFILE 'C:\EduQuizSolutions\datafiles\ts_datos' SIZE 50M
AUTOEXTEND ON
NEXT 50M
MAXSIZE 1000M;

CREATE TABLESPACE ts_transacciones
DATAFILE 'C:\EduQuizSolutions\datafiles\ts_transacciones' SIZE 100M
AUTOEXTEND ON
NEXT 100M
MAXSIZE 1000M;

CREATE TABLESPACE ts_index
DATAFILE 'C:\EduQuizSolutions\datafiles\ts_index' SIZE 50M;

/*asignacion tablas a tablespace*/

ALTER TABLE asignaciones_estudiantes MOVE TABLESPACE ts_transacciones;
ALTER TABLE examenes MOVE TABLESPACE ts_transacciones;
ALTER TABLE asignaciones_preguntas MOVE TABLESPACE ts_transacciones;
ALTER TABLE respuestas_estudiantes MOVE TABLESPACE ts_transacciones;
ALTER TABLE preguntas MOVE TABLESPACE ts_transacciones;
ALTER TABLE respuestas MOVE TABLESPACE ts_transacciones;
ALTER TABLE bancopreguntas MOVE TABLESPACE ts_transacciones;

ALTER TABLE contenidos MOVE TABLESPACE ts_datos;
ALTER TABLE cursos MOVE TABLESPACE ts_datos;
ALTER TABLE docentes MOVE TABLESPACE ts_datos;
ALTER TABLE estados MOVE TABLESPACE ts_datos;
ALTER TABLE estudiantes MOVE TABLESPACE ts_datos;
ALTER TABLE instituciones MOVE TABLESPACE ts_datos;
ALTER TABLE materias MOVE TABLESPACE ts_datos;
ALTER TABLE temas MOVE TABLESPACE ts_datos;
ALTER TABLE tipospreguntas MOVE TABLESPACE ts_datos;
ALTER TABLE unidadesestudio MOVE TABLESPACE ts_datos;

/*cambios nombre index*/

ALTER INDEX ASIGNACIONES_ESTUDIANTES_PK RENAME TO ID_ASIGNACIONES_ESTUDIANTES;
ALTER INDEX ASIGNACIONES_PREGUNTAS_PK RENAME TO ID_ASIGNACIONES_PREGUNTAS;
ALTER INDEX BANCOPREGUNTAS_PK RENAME TO ID_BANCOSPREGUNTAS;
ALTER INDEX CONTENIDOS_PK RENAME TO ID_CONTENIDOS;
ALTER INDEX CURSOS_PK RENAME TO ID_CURSOS;
ALTER INDEX DOCENTES_PK RENAME TO ID_DOCENTES;
ALTER INDEX ESTADOS_PK RENAME TO ID_ESTADOS;
ALTER INDEX ESTUDIANTES_PK RENAME TO ID_ESTUDIANTES;
ALTER INDEX EXAMENES_PK RENAME TO ID_EXAMENES;
ALTER INDEX INSTITUCIONES_PK RENAME TO ID_INSTITUCIONES;
ALTER INDEX MATERIAS_PK RENAME TO ID_MATERIAS;
ALTER INDEX PREGUNTAS_PK RENAME TO ID_PREGUNTAS;
ALTER INDEX RESPUESTAS_ESTUDIANTES_PK RENAME TO ID_RESPUESTAS_ESTUDIANTES;
ALTER INDEX RESPUESTAS_PK RENAME TO ID_RESPUESTAS;
ALTER INDEX TEMAS_PK RENAME TO ID_TEMAS;
ALTER INDEX TIPOSPREGUNTAS_PK RENAME TO ID_TIPOSPREGUNTAS;
ALTER INDEX UNIDADESESTUDIO_PK RENAME TO ID_UNIDADESESTUDIO;

/*Creamos nuevos index*/

CREATE INDEX NOMBRE_INSTITUCIONES ON INSTITUCIONES(NOMBRENINSTITUCION);
CREATE INDEX NOMBRE_TEMAS ON TEMAS(NOMBRE);
CREATE INDEX NOMBRE_UNIDADES ON UNIDADESESTUDIO(NOMBRE_UNIDAD);
CREATE INDEX NOMBRE_CURSOS ON CURSOS(NOMBRECURSO);
CREATE INDEX NOMBRE_MATERIAS ON MATERIAS(NOMBRE);

/*movemos los index a su tablespace*/
ALTER INDEX ID_ASIGNACIONES_ESTUDIANTES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_ASIGNACIONES_PREGUNTAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_BANCOSPREGUNTAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_CONTENIDOS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_CURSOS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_DOCENTES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_ESTADOS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_ESTUDIANTES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_EXAMENES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_INSTITUCIONES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_MATERIAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_PREGUNTAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_RESPUESTAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_RESPUESTAS_ESTUDIANTES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_TEMAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_TIPOSPREGUNTAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX ID_UNIDADESESTUDIO REBUILD TABLESPACE TS_INDEX;
ALTER INDEX NOMBRE_CURSOS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX NOMBRE_INSTITUCIONES REBUILD TABLESPACE TS_INDEX;
ALTER INDEX NOMBRE_MATERIAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX NOMBRE_TEMAS REBUILD TABLESPACE TS_INDEX;
ALTER INDEX NOMBRE_UNIDADES REBUILD TABLESPACE TS_INDEX;
